apiVersion: apps/v1
kind: Deployment
metadata:
  name: kakitu-middleware-kakitu
  namespace: kakitu-middleware
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kakitu-middleware-kakitu
  template:
    metadata:
      labels:
        app: kakitu-middleware-kakitu
    spec:
      containers:
      - name: kakitu-middleware-kakitu
        image: kakitucurrency/kakitu-middleware:2.0.0
        command: ["/bin/bash", "-c"]
        args: ["python main.py --host 0.0.0.0 --port 5555 --callbacks http://monkeytalks.monkeytalks:5000/callback http://graham-kakitu.graham-kakitu:11337/callback http://kakitubot.graham-kakitu:11337/callback http://kalium-server.kalium:3000/callback"]
        ports:
        - containerPort: 5555
          name: api
        env:
          - name: REDIS_HOST
            value: redis.redis
          - name: REDIS_DB
            value: "0"
          - name: BPOW_KEY
            valueFrom:
              secretKeyRef:
                name: kakitu-middleware
                key: bpow_key
---
apiVersion: v1
kind: Service
metadata:
  name: kakitu-middleware-kakitu
  namespace: kakitu-middleware
spec:
  type: ClusterIP
  ports:
  - port: 5555
    targetPort: 5555
    name: api
  selector:
    app: kakitu-middleware-kakitu
---
apiVersion: v1
kind: Service
metadata:
  name: kakitu-middleware-kakitu-nodeport
  namespace: kakitu-middleware
spec:
  type: NodePort
  ports:
  - name: api
    port: 5555
    nodePort: 30756
    targetPort: 5555
  selector:
    app: kakitu-middleware-kakitu
