apiVersion: apps/v1
kind: Deployment
metadata:
  name: kakitu-middleware-kshs
  namespace: kakitu-middleware
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kakitu-middleware-kshs
  template:
    metadata:
      labels:
        app: kakitu-middleware-kshs
    spec:
      containers:
      - name: kakitu-middleware-kshs
        image: kakitucurrency/kakitu-middleware:2.0.0
        command: ["/bin/bash", "-c"]
        args: ["python main.py --host 0.0.0.0 --port 5555 --callbacks http://graham-kakitu.graham-kakitu:11337/callback http://graham-kakitu2.graham-kakitu:11337/callback http://kakitu-server.kakitu:3000/callback --bpow-kakitu-difficulty"]
        ports:
        - containerPort: 5555
          name: api
        env:
          - name: REDIS_HOST
            value: redis.redis
          - name: REDIS_DB
            value: "1"
          - name: BPOW_KEY
            valueFrom:
              secretKeyRef:
                name: kakitu-middleware
                key: bpow_key
---
apiVersion: v1
kind: Service
metadata:
  name: kakitu-middleware-kshs
  namespace: kakitu-middleware
spec:
  type: ClusterIP
  ports:
  - port: 5555
    targetPort: 5555
    name: api
  selector:
    app: kakitu-middleware-kshs
---
apiVersion: v1
kind: Service
metadata:
  name: kakitu-middleware-kshs-nodeport
  namespace: kakitu-middleware
spec:
  type: NodePort
  ports:
  - name: api
    port: 5555
    nodePort: 30755
    targetPort: 5555
  selector:
    app: kakitu-middleware-kshs
